# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

buildJava:
  stage: build
  image: maven:latest
  artifacts:
    paths:
      - java/target/*.jar
  tags:
    - maastro
  script:
    - cd ./java && mvn clean package
  only:
    - master
    
dockerize:
  stage: build
  tags:
    - maastro
  script:
    - docker login -u “$CI_REGISTRY_USER” -p “$CI_REGISTRY_PASSWORD” $CI_REGISTRY
    - cp ./java/target/*.jar ./container/
    - cd ./container/ && docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master
