# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

stages:
  - build
  - dockerize
  - acceptance
  - release

buildBackend:
  stage: build
  image: maven:3.5.3-jdk-8
  artifacts:
    paths:
      - java/target/*.jar
  tags:
    - maastro
  script:
    - cd ./java && mvn clean package
  only:
    - master
    
dockerizeBackend:
  stage: dockerize
  dependencies:
    - buildBackend
  tags:
    - maastro
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cp ./java/target/*.jar ./containers/backend/
    - cd ./containers/backend/ && docker build --pull -t "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA" .
    - docker tag "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
  only:
    - master

dockerizeFrontend:
  stage: dockerize
  tags:
    - maastro
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd ./containers/frontend/ && docker build --pull -t "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA" .
    - docker tag "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG"
  only:
    - master
