version: '2'
services:
    beslis_db:
        image: postgres:10.4
        volumes:
            - ./database/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=beslissamen
            - POSTGRES_PASSWORD=AblexaVerEsT
    beslis_backend:
        image: registry.gitlab.com/medicaldataworks/beslissamen/backend:master
        environment:
            - VIRTUAL_HOST=backend.beslissamen.local
            - VIRTUAL_PORT=8081
        links:
            - beslis_db:dbhost
        volumes:
            - ./containers/backend/application.yml:/app/application.yml
        depends_on:
            - "beslis_db"
    beslis_frontend:
        build: containers/frontend
        environment:
            - VIRTUAL_HOST=beslissamen.local
            - VIRTUAL_PORT=80
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
