version: '2'
services:
    beslis_db:
        image: postgres:10.4
        volumes:
            - ./database/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=beslissamen
            - POSTGRES_PASSWORD=AblexaVerEsT
    beslis_backend:
        image: registry.gitlab.com/medicaldataworks/beslissamen/backend
        ports:
            - 8081:8081
        links:
            - beslis_db:dbhost
        depends_on:
            - "beslis_db"
    beslis_frontend:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./website/:/usr/share/nginx/html:ro