version: '2'
services:
    beslissamen-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/beslissamen/beslissamenbackend/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=beslissamen
            - POSTGRES_PASSWORD=AblexaVerEsT
        ports:
            - 5432:5432
