name: Build WebUI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
      - 'release/**'

env:
  REGISTRY: ghcr.io

jobs:
  containerize:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v2
        if: steps.extract_branch.outputs.branch != 'master'
        with:
          context: ./containers/frontend
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
      - name: Build container
        id: docker_build_main
        uses: docker/build-push-action@v2
        if: steps.extract_branch.outputs.branch == 'master'
        with:
          context: ./containers/frontend
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}, ghcr.io/${{ env.REPO }}:latest