logging:
  level:
    nl.maastro: DEBUG

spring:
  datasource:
    url: jdbc:h2:file:./db/beslissamen;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update

swagger.enabled: true

cors.allowed-origins:
    - http://localhost